type Country {
  id: Int
  name: String
}

type Query {
  countries: [Country]
}

input CountryInput {
  name: String!
  locale: String!
}

type Mutation {
  createCountry(input: [CountryInput!]!): Country
  updateCountry(id: Int!, input: [CountryInput!]!): Country
  deleteCountry(id: Int!): Country
}
