type Query {
  activities(take: Int, skip: Int): [Activitiy]
  activitiesEnabled(take: Int, skip: Int): [Activitiy]
  activityBySlug(slug: String!): Activitiy
}

type Mutation {
  createActivitiy(input: ActivitiyInput): Activitiy
  updateActivitiy(id: Int!, input: ActivitiyInput): Activitiy
  deleteActivitiy(id: Int!): Activitiy
}

type Activitiy {
	id: Int
  type: String
  slug: String
  title: String
  excerpt: String
  content: String
	description: String
  button_link: String
  button_text: String
	feature_image_src: String
	feature_image_alt: String
	og_image_src: String
  created_on:  String
  created_by:  String
  updated_by: String
  read_count: Int
	is_disabled: Int
  level: String
  classification: String
  started_on: String
  end_on: String
  images: [ActivitiyImage]
}

type ActivitiyImage {
  id: Int
  title: String
  image_src: String
  image_alt: String
}

input ActivitiyInput {
  type: String
  slug: String
	description: String
  button_link: String
	feature_image_src: String
	feature_image_alt: String
	og_image_src: String
  "m/d/yyyy hh:MM:ss"
  created_by:  String
  "m/d/yyyy hh:MM:ss"
  level_id: Int
  classification_id: Int
  started_on: String
  end_on: String
  locales: [LocaleActivitiy!]!
}

input LocaleActivitiy {
  title: String
  excerpt: String
  content: String
  button_text: String
  locale: String!
}

input ActivitiyImageInput {
  image_src: String
  image_alt: String
  locales: [LocaleActivitiyImage]
}

input LocaleActivitiyImage {
  title: String
  locale: String
}


  
