type Category {
  id: Int
  slug: String
  img_src: String
  img_alt: String
  is_disabled: Int
  name: String
}

type Query {
  categories: [Category]
}

input CategoryInput {
  slug: String!
  img_src: String
  img_alt: String
  is_disabled: Int
  locales: Locales[!]!
}

input Locales {
  name: String!
  locale: String!
}

type Mutation {
  createCategory(input: CategoryInput): Category
  updateCategory(id: Int!, input: [CategoryInput!]!): Category
  deleteCategory(id: Int!): Category
}
